// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.autoCommands;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.BBCommand;
import org.usfirst.frc330.Robot;
import org.usfirst.frc330.autoCommands.CenterStart_Switch.SwitchPosition;
import org.usfirst.frc330.util.Logger;
import org.usfirst.frc330.util.Logger.Severity;

/**
 *
 */
public class CenterStart_Switch_Chooser extends BBCommand {
	
	String gameData;
	
    public CenterStart_Switch_Chooser() {
    	this.setRunWhenDisabled(false);
    }

    protected void initialize() {
		
    }


    protected void execute() {
    	gameData = DriverStation.getInstance().getGameSpecificMessage();
		if(gameData.length() > 0) {
			if(gameData.charAt(0) == 'L') {
				new CenterStart_Switch(SwitchPosition.LEFT).start();
				Logger.getInstance().println("Our Switch is on the left", Severity.INFO);
			}
			else if (gameData.charAt(0) == 'R') {
				new CenterStart_Switch(SwitchPosition.RIGHT).start();
				Logger.getInstance().println("Our Switch is on the right", Severity.INFO);
			}
			else {
				Logger.getInstance().println("Unknown gameData: " + gameData, Severity.ERROR);
			}
		}
    }

    protected boolean isFinished() {
        return gameData.length() > 0;
    }

    protected void end() {
    }


    protected void interrupted() {
    }
}
