// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;
import edu.wpi.first.wpilibj.command.BBCommand;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.commands.drivecommands.Waypoint;
import org.usfirst.frc330.util.Logger;

/**
 *
 */
public class PredictiveCommand extends BBCommand {

	Waypoint wp;
	double distance;
	Command command;
	
    public PredictiveCommand(Waypoint wp, double distance, Command command) {
    	this.setRunWhenDisabled(false);
    	this.wp = wp;
    	this.distance = distance;
    	this.command = command;
    }

    protected void initialize() {
    	Logger.getInstance().println("Current Postition: " + Robot.chassis.getX() + ", " + Robot.chassis.getY(), Logger.Severity.INFO);
    	Logger.getInstance().println("Run command at distance: " + distance, Logger.Severity.INFO);
    	Logger.getInstance().println("Command name: " + command, Logger.Severity.INFO);
    }


    protected void execute() {
    	
    }

    protected boolean isFinished() {
    	double aSQ = Math.pow((wp.getX() - Robot.chassis.getX()), 2);
    	double bSQ = Math.pow((wp.getY() - Robot.chassis.getY()), 2);
    	return (Math.sqrt(aSQ+bSQ) < distance);
    }

    protected void end() {
    	command.start();
    	Robot.grabber.closeClaw();
    	Logger.getInstance().println("Position when initiating command: " + Robot.chassis.getX() + ", " + Robot.chassis.getY(), Logger.Severity.INFO);
    }


    protected void interrupted() {
    }
}
