// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;
import edu.wpi.first.wpilibj.command.BBCommand;
import org.usfirst.frc330.Robot;
import org.usfirst.frc330.constants.GrabberConst;
import org.usfirst.frc330.util.Logger;
import org.usfirst.frc330.util.Logger.Severity;

/**
 *
 */
public class RollerUntilCube extends BBCommand {
	double minTime;

    public RollerUntilCube() {
    	this(0.45, 0.75);
    }
    
    public RollerUntilCube(double maxTimeout) {
    	this(0.25, maxTimeout);
    }
    
    public RollerUntilCube(double minTime, double maxTimeout) {

        requires(Robot.grabber);

        this.setTimeout(maxTimeout);
        this.minTime = minTime;
        if (maxTimeout < minTime) {
        	throw new IllegalArgumentException("maxTimeout (" + maxTimeout + 
        			") must be larger then minTime (" + minTime + ")");
        }
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	Robot.grabber.rollerOn();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return (isTimedOut() || Robot.grabber.getSensorCDistance() < GrabberConst.sensorMaximumInnerDistance+1) && this.timeSinceInitialized() > minTime;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.grabber.rollerOff();
    	Logger.getInstance().println("Center Sensor Distance: " + Robot.grabber.getSensorCDistance(), Severity.INFO);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	this.end();
    }
}
