// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;
import edu.wpi.first.wpilibj.command.BBCommand;
import org.usfirst.frc330.Robot;
import org.usfirst.frc330.constants.LiftConst;
import org.usfirst.frc330.util.Logger;

import com.ctre.phoenix.motorcontrol.ControlMode;

/**
 *
 */
public class Taller extends BBCommand {

    public Taller() {

    	//requires(Robot.lift);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	if(Robot.lift.getMode() == ControlMode.Position || Robot.lift.getMode() == ControlMode.MotionMagic) {
    		Logger.getInstance().println("Current Setpoint: " + Robot.lift.getSetpoint(), Logger.Severity.INFO);
        	Robot.lift.setLiftPosition(Robot.lift.getSetpoint() + LiftConst.stepSize);
    		//Robot.lift.setLiftPosition(10);
    	}
    	else {
    		Logger.getInstance().println("Lift in mode: " + Robot.lift.getMode(), Logger.Severity.WARNING);
    		Logger.getInstance().println("Current position: " + Robot.lift.getPosition(), Logger.Severity.INFO);
        	Robot.lift.setLiftPosition(Robot.lift.getPosition() + LiftConst.stepSize);
    	}
    	
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    	//return Robot.lift.getLiftOnTarget();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Logger.getInstance().println("Final Setpoint: " + Robot.lift.getSetpoint(), Logger.Severity.INFO);
    	Logger.getInstance().println("Final Position: " + Robot.lift.getPosition(), Logger.Severity.INFO);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	this.end();
    }
}
