// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.commandgroups;

import edu.wpi.first.wpilibj.command.BBCommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

import org.usfirst.frc330.commands.CoordinatedMove;
import org.usfirst.frc330.commands.IsFinishedFalse;
import org.usfirst.frc330.commands.LoopIfWeHaveCube;
import org.usfirst.frc330.commands.OpenClaw;
import org.usfirst.frc330.commands.RollerOn;
import org.usfirst.frc330.commands.RollerUntilCube;
import org.usfirst.frc330.commands.SensorCloseClaw;
import org.usfirst.frc330.commands.SetHandAngle;
import org.usfirst.frc330.commands.SetLiftPosition;
import org.usfirst.frc330.constants.ArmConst;
import org.usfirst.frc330.constants.HandConst;
import org.usfirst.frc330.constants.LiftConst;
import org.usfirst.frc330.subsystems.*;

/**
 *
 */
public class SensorlessPickupDown extends BBCommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public SensorlessPickupDown() {
    	
    	//open grabber
    	addSequential(new OpenClaw());
    	
    	addParallel(new SetLiftPosition(LiftConst.intakePosition));
    	addSequential(new CoordinatedMove(ArmConst.intakePosition, HandConst.e_pickup));
    	
    	addSequential(new RollerOn());

    	addSequential(new IsFinishedFalse());
 
    } 
}
