// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330;

import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.commands.commandgroups.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
//import org.usfirst.frc330.commands.commandgroups.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton shiftLow_1;
    public Joystick driverL;
    public JoystickButton shiftHigh_1;
    public JoystickButton climb_1;
    public Joystick driverR;
    public Joystick armGamePad;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        armGamePad = new Joystick(2);
        
        driverR = new Joystick(1);
        
        climb_1 = new JoystickButton(driverR, 2);
        climb_1.whileHeld(new ClimbHeld());
        shiftHigh_1 = new JoystickButton(driverR, 1);
        shiftHigh_1.whenPressed(new ShiftHigh());
        driverL = new Joystick(0);
        
        shiftLow_1 = new JoystickButton(driverL, 1);
        shiftLow_1.whenPressed(new ShiftLow());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("ShiftLow", new ShiftLow());
        SmartDashboard.putData("ShiftHigh", new ShiftHigh());
        SmartDashboard.putData("OpenClaw", new OpenClaw());
        SmartDashboard.putData("CloseClaw", new CloseClaw());
        SmartDashboard.putData("SensorCloseClaw", new SensorCloseClaw());
        SmartDashboard.putData("ManualLift", new ManualLift());
        SmartDashboard.putData("UnlockPlatforms", new UnlockPlatforms());
        SmartDashboard.putData("ManualArm", new ManualArm());
        SmartDashboard.putData("ManualWrist", new ManualWrist());
        SmartDashboard.putData("RollerOn", new RollerOn());
        SmartDashboard.putData("RollerOff", new RollerOff());
        SmartDashboard.putData("RollerReverse", new RollerReverse());
        SmartDashboard.putData("RollerReverseOff", new RollerReverseOff());
        SmartDashboard.putData("ClimbHeld", new ClimbHeld());
        SmartDashboard.putData("DeployCube", new DeployCube());
        SmartDashboard.putData("IntakeCube", new IntakeCube());
        SmartDashboard.putData("dropoffPositionSwitch", new dropoffPositionSwitch());
        SmartDashboard.putData("dropoffPositionLow", new dropoffPositionLow());
        SmartDashboard.putData("dropoffPositionMed", new dropoffPositionMed());
        SmartDashboard.putData("dropoffPositionMax", new dropoffPositionMax());
        SmartDashboard.putData("Defense", new Defense());
        SmartDashboard.putData("ClimbReady", new ClimbReady());
        SmartDashboard.putData("FlipWrist", new FlipWrist());
        SmartDashboard.putData("IntakePortal", new IntakePortal());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriverL() {
        return driverL;
    }

    public Joystick getDriverR() {
        return driverR;
    }

    public Joystick getarmGamePad() {
        return armGamePad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

