// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330;

import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.util.WPILibVersion;

import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.subsystems.*;
//import org.usfirst.frc330.subsystems.Frills.Alarm;
import org.usfirst.frc330.util.BeachbotLibVersion;
import org.usfirst.frc330.util.Buzzer;
import org.usfirst.frc330.util.CSVLogger;
import org.usfirst.frc330.util.Logger;
import org.usfirst.frc330.util.Logger.Severity;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {

    Command autonomousCommand;
    SendableChooser<Command> chooser = new SendableChooser<>();

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Chassis chassis;
    public static Lift lift;
    public static Arm arm;
    public static Grabber grabber;
    public static Climber climber;
    public static Frills frills;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static Buzzer buzzer;
    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassis = new Chassis();
        SmartDashboard.putData(chassis);
        lift = new Lift();
        SmartDashboard.putData(lift);
        arm = new Arm();
        SmartDashboard.putData(arm);
        grabber = new Grabber();
        SmartDashboard.putData(grabber);
        climber = new Climber();
        SmartDashboard.putData(climber);
        frills = new Frills();
        SmartDashboard.putData(frills);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        //TODO Allen: figure out how to implement the buzzer without RobotMap
        //buzzer = new Buzzer(RobotMap.frillsBuzzer);
        
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();
        
        // Setup Cameras --------------------------------------------------------
        frills.initDriverCamera();
        // </Cameras> -------------------------------------------------------------

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        chooser.addDefault("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
        
        // ---------------------------------------------------------------------
        // Logging
        // ---------------------------------------------------------------------
        CSVLogger.getInstance().writeHeader();
        
        Logger.getInstance().println("BeachbotLib Version:        " + BeachbotLibVersion.Version, Severity.INFO);
        Logger.getInstance().println("WPILib Version: "             + WPILibVersion.Version, Severity.INFO);
        //TODO Port the following two lines of code:
        //Logger.getInstance().println("NavX Firmware Version:      " + RobotMap.chassisImu.getFirmwareVersion(), Severity.INFO);
        //Logger.getInstance().println("CAN Talon Firmware Version: " + RobotMap.shooterShooter.GetFirmwareVersion(), Severity.INFO);
        

        if (getIsPracticeRobot())
        	Logger.getInstance().println("Practice Robot Detected",true);
        else
        	Logger.getInstance().println("Competition Robot Detected",true);
    
        buzzer.enable(0.75);
        // </Logging> ----------------------------------------------------------

        
        
        SmartDashboard.putData("Auto mode", chooser);
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){
    	//VERIFY copy over code from 2017 (and update it of course!) -mf
    	Logger.getInstance().println("Disabled Init",true);
		Scheduler.getInstance().removeAll();
		Robot.grabber.closeClaw();
		Robot.chassis.setPTOdisengaged();
		Robot.lift.stopLift();
		//Robot.pickup.gearRelease();
		Robot.climber.lockPlatforms();
		Robot.arm.stopArm();
		Robot.arm.stopWrist();
		Robot.grabber.pickupOff();
		Robot.chassis.stopDrive();
    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
        //VERIFY copy over code from 2017 (and update it of course!) -JB
        chassis.calcXY();
    	CSVLogger.getInstance().writeData();
    	Logger.getInstance().updateDate();
    	CSVLogger.getInstance().updateDate();
    	buzzer.update();
    	//if (frills.getAlarmLEDs() == Alarm.SLOW && !Robot.chassis.isGyroCalibrating()) {
    	//	frills.setAlarmLED(Alarm.OFF);
    	}
    
    @Override
    public void autonomousInit() {
        autonomousCommand = chooser.getSelected();
        // schedule the autonomous command (example)
        if (autonomousCommand != null) autonomousCommand.start();
        //TODO copy over code from 2017 (and update it of course!)
        
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
    	chassis.calcXY();

        Scheduler.getInstance().run();
        //VERIFY copy over code from 2017 (and update it of course!)-JB
        chassis.pidDriveAuto();
    	CSVLogger.getInstance().writeData();
		buzzer.update();
    }

    @Override
    public void teleopInit() {
        //VERIFY copy over code from 2017 (and update it of course!)
        Logger.getInstance().println("Teleop Init", true);
    	Logger.getInstance().updateDate();
    	CSVLogger.getInstance().updateDate();
    	buzzer.enable(1.25);
    	Robot.climber.lockPlatforms();
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        //VERIFY copy over code from 2017 (and update it of course!) -JB
            chassis.calcXY();
            Scheduler.getInstance().run();
            chassis.pidDrive();
        	CSVLogger.getInstance().writeData();
        	buzzer.update();
        }
    
    
    // -----------------------------------------------------------
    // Get Methods
    // -----------------------------------------------------------
    public boolean getIsPracticeRobot() {
    	return frills.getIsPracticeRobot();
    }
    //other
    
}
